openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for project-service
paths:
    /livez:
        get:
            tags:
                - project-service
            summary: livez project-service
            description: Check if the service is alive.
            operationId: project-service#livez
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: OK
                                format: binary
                            example: OK
    /openapi.json:
        get:
            tags:
                - project-service
            summary: Download gen/http/openapi3.json
            operationId: project-service#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /projects:
        get:
            tags:
                - project-service
            summary: get-projects project-service
            description: Get all projects.
            operationId: project-service#get-projects
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
            responses:
                "200":
                    description: OK response.
                    headers:
                        Cache-Control:
                            description: Cache control header
                            schema:
                                type: string
                                description: Cache control header
                                example: public, max-age=300
                            example: public, max-age=300
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetProjectsResponseBody'
                            example:
                                projects:
                                    - auditors:
                                        - user123
                                        - user456
                                      description: project foo is a project about bar
                                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      name: Foo Foundation
                                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      public: true
                                      slug: project-slug
                                      writers:
                                        - user123
                                        - user456
                                    - auditors:
                                        - user123
                                        - user456
                                      description: project foo is a project about bar
                                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      name: Foo Foundation
                                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      public: true
                                      slug: project-slug
                                      writers:
                                        - user123
                                        - user456
                                    - auditors:
                                        - user123
                                        - user456
                                      description: project foo is a project about bar
                                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      name: Foo Foundation
                                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                      public: true
                                      slug: project-slug
                                      writers:
                                        - user123
                                        - user456
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                code: "400"
                                message: The request was invalid.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: "500"
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
        post:
            tags:
                - project-service
            summary: create-project project-service
            description: Create a new project.
            operationId: project-service#create-project
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateProjectRequestBody'
                        example:
                            auditors:
                                - user123
                                - user456
                            description: project foo is a project about bar
                            name: Foo Foundation
                            parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                            public: true
                            slug: project-slug
                            writers:
                                - user123
                                - user456
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Project'
                            example:
                                auditors:
                                    - user123
                                    - user456
                                description: project foo is a project about bar
                                id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                name: Foo Foundation
                                parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                public: true
                                slug: project-slug
                                writers:
                                    - user123
                                    - user456
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                code: "400"
                                message: The request was invalid.
                "409":
                    description: 'Conflict: Conflict'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConflictError'
                            example:
                                code: "409"
                                message: The resource already exists.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: "500"
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
    /projects/{id}:
        delete:
            tags:
                - project-service
            summary: delete-project project-service
            description: Delete an existing project.
            operationId: project-service#delete-project
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
                - name: id
                  in: path
                  description: Project ID -- v2 id, not related to v1 id directly
                  required: true
                  schema:
                    type: string
                    description: Project ID -- v2 id, not related to v1 id directly
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                    format: uuid
                  example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                - name: ETag
                  in: header
                  description: ETag header value
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: ETag header value
                    example: "123"
                  example: "123"
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                code: "400"
                                message: The request was invalid.
                "404":
                    description: 'NotFound: Resource not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFoundError'
                            example:
                                code: "404"
                                message: The resource was not found.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: "500"
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
        get:
            tags:
                - project-service
            summary: get-one-project project-service
            description: Get a single project.
            operationId: project-service#get-one-project
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
                - name: id
                  in: path
                  description: Project ID -- v2 id, not related to v1 id directly
                  required: true
                  schema:
                    type: string
                    description: Project ID -- v2 id, not related to v1 id directly
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                    format: uuid
                  example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
            responses:
                "200":
                    description: OK response.
                    headers:
                        ETag:
                            description: ETag header value
                            schema:
                                type: string
                                description: ETag header value
                                example: Sequi laboriosam quis quas.
                            example: Rerum odio omnis ipsum.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Project'
                            example:
                                auditors:
                                    - user123
                                    - user456
                                description: project foo is a project about bar
                                id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                name: Foo Foundation
                                parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                public: true
                                slug: project-slug
                                writers:
                                    - user123
                                    - user456
                "404":
                    description: 'NotFound: Resource not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFoundError'
                            example:
                                code: "404"
                                message: The resource was not found.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: "500"
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
        put:
            tags:
                - project-service
            summary: update-project project-service
            description: Update an existing project.
            operationId: project-service#update-project
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
                - name: id
                  in: path
                  description: Project ID -- v2 id, not related to v1 id directly
                  required: true
                  schema:
                    type: string
                    description: Project ID -- v2 id, not related to v1 id directly
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                    format: uuid
                  example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                - name: ETag
                  in: header
                  description: ETag header value
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: ETag header value
                    example: "123"
                  example: "123"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateProjectRequestBody'
                        example:
                            auditors:
                                - user123
                                - user456
                            description: project foo is a project about bar
                            name: Foo Foundation
                            parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                            public: true
                            slug: project-slug
                            writers:
                                - user123
                                - user456
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Project'
                            example:
                                auditors:
                                    - user123
                                    - user456
                                description: project foo is a project about bar
                                id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                name: Foo Foundation
                                parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                                public: true
                                slug: project-slug
                                writers:
                                    - user123
                                    - user456
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                code: "400"
                                message: The request was invalid.
                "404":
                    description: 'NotFound: Resource not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFoundError'
                            example:
                                code: "404"
                                message: The resource was not found.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: "500"
                                message: An internal server error occurred.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
            security:
                - jwt_header_Authorization: []
    /readyz:
        get:
            tags:
                - project-service
            summary: readyz project-service
            description: Check if the service is able to take inbound requests.
            operationId: project-service#readyz
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: OK
                                format: binary
                            example: OK
                "503":
                    description: 'ServiceUnavailable: Service is unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: "503"
                                message: The service is unavailable.
components:
    schemas:
        BadRequestError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: "400"
                message:
                    type: string
                    description: Error message
                    example: The request was invalid.
            example:
                code: "400"
                message: The request was invalid.
            required:
                - code
                - message
        ConflictError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: "409"
                message:
                    type: string
                    description: Error message
                    example: The resource already exists.
            example:
                code: "409"
                message: The resource already exists.
            required:
                - code
                - message
        CreateProjectRequestBody:
            type: object
            properties:
                auditors:
                    type: array
                    items:
                        type: string
                        example: Quae ex voluptate voluptatem magnam quos eos.
                    description: A list of project auditors by their user IDs
                    example:
                        - user123
                        - user456
                description:
                    type: string
                    description: A description of the project
                    example: project foo is a project about bar
                name:
                    type: string
                    description: The pretty name of the project
                    example: Foo Foundation
                parent_uid:
                    type: string
                    description: The UID of the parent project, should be empty if there is none
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                public:
                    type: boolean
                    description: Whether the project is public
                    example: true
                slug:
                    type: string
                    description: Project slug, a short slugified name of the project
                    example: project-slug
                    format: regexp
                    pattern: ^[a-z][a-z0-9_\-]*[a-z0-9]$
                writers:
                    type: array
                    items:
                        type: string
                        example: Voluptas et quibusdam veritatis sed quis.
                    description: A list of project writers by their user IDs
                    example:
                        - user123
                        - user456
            example:
                auditors:
                    - user123
                    - user456
                description: project foo is a project about bar
                name: Foo Foundation
                parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                public: true
                slug: project-slug
                writers:
                    - user123
                    - user456
            required:
                - slug
                - description
                - name
        GetProjectsResponseBody:
            type: object
            properties:
                projects:
                    type: array
                    items:
                        $ref: '#/components/schemas/Project'
                    description: Resources found
                    example:
                        - auditors:
                            - user123
                            - user456
                          description: project foo is a project about bar
                          id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          name: Foo Foundation
                          parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          public: true
                          slug: project-slug
                          writers:
                            - user123
                            - user456
                        - auditors:
                            - user123
                            - user456
                          description: project foo is a project about bar
                          id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          name: Foo Foundation
                          parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          public: true
                          slug: project-slug
                          writers:
                            - user123
                            - user456
                        - auditors:
                            - user123
                            - user456
                          description: project foo is a project about bar
                          id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          name: Foo Foundation
                          parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          public: true
                          slug: project-slug
                          writers:
                            - user123
                            - user456
                        - auditors:
                            - user123
                            - user456
                          description: project foo is a project about bar
                          id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          name: Foo Foundation
                          parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                          public: true
                          slug: project-slug
                          writers:
                            - user123
                            - user456
            example:
                projects:
                    - auditors:
                        - user123
                        - user456
                      description: project foo is a project about bar
                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      name: Foo Foundation
                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      public: true
                      slug: project-slug
                      writers:
                        - user123
                        - user456
                    - auditors:
                        - user123
                        - user456
                      description: project foo is a project about bar
                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      name: Foo Foundation
                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      public: true
                      slug: project-slug
                      writers:
                        - user123
                        - user456
                    - auditors:
                        - user123
                        - user456
                      description: project foo is a project about bar
                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      name: Foo Foundation
                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      public: true
                      slug: project-slug
                      writers:
                        - user123
                        - user456
                    - auditors:
                        - user123
                        - user456
                      description: project foo is a project about bar
                      id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      name: Foo Foundation
                      parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                      public: true
                      slug: project-slug
                      writers:
                        - user123
                        - user456
            required:
                - projects
        InternalServerError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: "500"
                message:
                    type: string
                    description: Error message
                    example: An internal server error occurred.
            example:
                code: "500"
                message: An internal server error occurred.
            required:
                - code
                - message
        NotFoundError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: "404"
                message:
                    type: string
                    description: Error message
                    example: The resource was not found.
            example:
                code: "404"
                message: The resource was not found.
            required:
                - code
                - message
        Project:
            type: object
            properties:
                auditors:
                    type: array
                    items:
                        type: string
                        example: Aperiam omnis tenetur.
                    description: A list of project auditors by their user IDs
                    example:
                        - user123
                        - user456
                description:
                    type: string
                    description: A description of the project
                    example: project foo is a project about bar
                id:
                    type: string
                    description: Project ID -- v2 id, not related to v1 id directly
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                    format: uuid
                name:
                    type: string
                    description: The pretty name of the project
                    example: Foo Foundation
                parent_uid:
                    type: string
                    description: The UID of the parent project, should be empty if there is none
                    example: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                public:
                    type: boolean
                    description: Whether the project is public
                    example: true
                slug:
                    type: string
                    description: Project slug, a short slugified name of the project
                    example: project-slug
                    format: regexp
                    pattern: ^[a-z][a-z0-9_\-]*[a-z0-9]$
                writers:
                    type: array
                    items:
                        type: string
                        example: Doloribus ratione debitis molestiae ut dolorum id.
                    description: A list of project writers by their user IDs
                    example:
                        - user123
                        - user456
            description: A representation of LFX Projects.
            example:
                auditors:
                    - user123
                    - user456
                description: project foo is a project about bar
                id: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                name: Foo Foundation
                parent_uid: 7cad5a8d-19d0-41a4-81a6-043453daf9ee
                public: true
                slug: project-slug
                writers:
                    - user123
                    - user456
        ServiceUnavailableError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: "503"
                message:
                    type: string
                    description: Error message
                    example: The service is unavailable.
            example:
                code: "503"
                message: The service is unavailable.
            required:
                - code
                - message
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Heimdall authorization
            scheme: bearer
tags:
    - name: project-service
      description: The project service provides LFX Project resources.
